DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"CLIENTE" (
    "RUC" NVARCHAR2(20) NOT NULL,
    "RAZON_SOCIAL" NVARCHAR2(200) NOT NULL,
    "TELEFONO_CONTACTO" NUMBER(18,0) NOT NULL,
    "CORREO_CONTACTO" NVARCHAR2(200) NOT NULL,
    "DIRECCION" NVARCHAR2(300),
    CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("RUC")
)';
END;
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20251030202129_InitialCreate', N'9.0.10')
/

